spring.datasource.url=jdbc:mysql://localhost:3306/polovni_pj_2026?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
